#!/bin/bash
# Generic Backup Script
# Generated by backup-utils.sh

SOURCE="{{SOURCE_DIR}}"
DESTINATION="{{BACKUP_DEST}}"
BACKUP_RETENTION={{BACKUP_RETENTION}}
DATE=$(date +%Y-%m-%d_%H%M%S)

echo "--- Starting Backup $DATE for {{SERVICE_NAME}} ---"

# Create date-stamped backup folder
BACKUP_DIR="$DESTINATION/$DATE"
mkdir -p "$BACKUP_DIR"

# Sync Data
echo "Syncing data from $SOURCE to $BACKUP_DIR..."
# Exclude commonly ignored files
# Update / Check incremental base via 'latest' symlink
LINK_DEST_ARG=""
if [ -d "$DESTINATION/latest" ]; then
    LINK_DEST_ARG="--link-dest=$DESTINATION/latest"
fi

# Sync Data
echo "Syncing data from $SOURCE to $BACKUP_DIR..."
rsync -av $LINK_DEST_ARG \
    --exclude '.git' \
    --exclude 'node_modules' \
    --exclude '*.log' \
    "$SOURCE/" "$BACKUP_DIR/"

# Update 'latest' symlink
ln -sfn "$BACKUP_DIR" "$DESTINATION/latest"

# Prune old backups (keep only the newest $BACKUP_RETENTION)
if [[ "$BACKUP_RETENTION" =~ ^[0-9]+$ ]] && [ "$BACKUP_RETENTION" -gt 0 ]; then
    echo "Pruning old backups (keeping $BACKUP_RETENTION)..."
    cd "$DESTINATION" || exit 1
    
    # Säkrare sätt att lista mappar sorterat på tid utan ls-pipe:
    find . -maxdepth 1 -type d -name "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_*" -printf '%T@ %p\n' | \
    sort -nr | tail -n +$((BACKUP_RETENTION + 1)) | cut -d' ' -f2- | while read -r old_dir; do
        if [ -d "$old_dir" ]; then
            echo "Removing old backup: $old_dir"
            rm -rf "$old_dir"
        fi
    done
else
    echo "Warning: Invalid BACKUP_RETENTION ($BACKUP_RETENTION). Skipping pruning for safety."
fi

echo "--- Backup Completed ---"
