#!/bin/bash
# Postgres Service Backup Script
# Generated by backup-utils.sh

SOURCE="{{SOURCE_DIR}}"
DESTINATION="{{BACKUP_DEST}}"
DB_CONTAINER="{{DB_CONTAINER}}"
DB_USER="postgres" # Default, might need customization
DATE=$(date +%Y-%m-%d_%H%M%S)

echo "--- Starting Backup $DATE for {{SERVICE_NAME}} ---"

mkdir -p "$DESTINATION"
mkdir -p "$DESTINATION/db-dumps"

# 1. Dump Database
echo "Dumping database from $DB_CONTAINER..."
if docker ps | grep -q "$DB_CONTAINER"; then
    docker exec -t "$DB_CONTAINER" pg_dumpall -c -U "$DB_USER" > "$DESTINATION/db-dumps/db_dump_$DATE.sql"
    # Keep latest link
    cp "$DESTINATION/db-dumps/db_dump_$DATE.sql" "$DESTINATION/db-dumps/latest.sql"
    
    # Cleanup old dumps (keep last 7 days)
    find "$DESTINATION/db-dumps/" -name "db_dump_*.sql" -mtime +7 -delete
else
    echo "Warning: Container $DB_CONTAINER not running. Skipping DB dump."
fi

# 2. Sync Files
echo "Syncing data from $SOURCE to $DESTINATION..."
rsync -av --delete \
    --exclude '.git' \
    --exclude 'node_modules' \
    --exclude '*.log' \
    --exclude 'postgres-data' \
    "$SOURCE/" "$DESTINATION/"

echo "--- Backup Completed ---"
