#!/bin/bash
# Generic Backup Script
# Generated by backup-utils.sh

SOURCE="{{SOURCE_DIR}}"
DESTINATION="{{BACKUP_DEST}}"
DATE=$(date +%Y-%m-%d_%H%M%S)

echo "--- Starting Backup $DATE for {{SERVICE_NAME}} ---"

mkdir -p "$DESTINATION"

# Sync Data
echo "Syncing data from $SOURCE to $DESTINATION..."
# Exclude commonly ignored files
rsync -av --delete \
    --exclude '.git' \
    --exclude 'node_modules' \
    --exclude '*.log' \
    "$SOURCE/" "$DESTINATION/"

echo "--- Backup Completed ---"
