#!/bin/bash
# Postgres Service Backup Script
# Generated by backup-utils.sh

# Source config for container engine settings
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/../read-config.sh" ]; then
    source "$SCRIPT_DIR/../read-config.sh"
elif [ -f "$SCRIPT_DIR/../../scripts/read-config.sh" ]; then
    source "$SCRIPT_DIR/../../scripts/read-config.sh"
fi

SOURCE="{{SOURCE_DIR}}"
DESTINATION="{{BACKUP_DEST}}"
DB_CONTAINER="{{DB_CONTAINER}}"
DB_USER="postgres" # Default, might need customization
BACKUP_RETENTION={{BACKUP_RETENTION}}
DATE=$(date +%Y-%m-%d_%H%M%S)

echo "--- Starting Backup $DATE for {{SERVICE_NAME}} ---"

# Create date-stamped backup folder
BACKUP_DIR="$DESTINATION/$DATE"
mkdir -p "$BACKUP_DIR"

# 1. Dump Database
echo "Dumping database from $DB_CONTAINER..."
if $CONTAINER_CMD ps --format '{{.Names}}' | grep -Eq "^${DB_CONTAINER}$"; then
    if ! $CONTAINER_CMD exec -t "$DB_CONTAINER" pg_dumpall -c -U "$DB_USER" > "$BACKUP_DIR/db_dump.sql"; then
        echo "ERROR: Database dump failed!" >&2
        exit 1
    fi
else
    echo "ERROR: Container $DB_CONTAINER not running. Aborting backup to prevent data loss!" >&2
    exit 1
fi

# 2. Sync Files
# Update / Check incremental base via 'latest' symlink
LINK_DEST_ARG=""
if [ -d "$DESTINATION/latest" ]; then
    LINK_DEST_ARG="--link-dest=$DESTINATION/latest"
fi

# 2. Sync Files
echo "Syncing data from $SOURCE to $BACKUP_DIR..."
rsync -av $LINK_DEST_ARG \
    --exclude '.git' \
    --exclude 'node_modules' \
    --exclude '*.log' \
    --exclude 'postgres-data' \
    "$SOURCE/" "$BACKUP_DIR/"

# Update 'latest' symlink
ln -sfn "$BACKUP_DIR" "$DESTINATION/latest"

# Prune old backups (keep only the newest $BACKUP_RETENTION)
if [[ "$BACKUP_RETENTION" =~ ^[0-9]+$ ]] && [ "$BACKUP_RETENTION" -gt 0 ]; then
    echo "Pruning old backups (keeping $BACKUP_RETENTION)..."
    cd "$DESTINATION" || exit 1
    
    # Säkrare sätt att lista mappar sorterat på tid utan ls-pipe:
    find . -maxdepth 1 -type d -name "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_*" -printf '%T@ %p\n' | \
    sort -nr | tail -n +$((BACKUP_RETENTION + 1)) | cut -d' ' -f2- | while read -r old_dir; do
        if [ -d "$old_dir" ]; then
            echo "Removing old backup: $old_dir"
            rm -rf "$old_dir"
        fi
    done
else
    echo "Warning: Invalid BACKUP_RETENTION ($BACKUP_RETENTION). Skipping pruning for safety."
fi

echo "--- Backup Completed ---"
