version: "3.8"

# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
   traccar:
      image: traccar/traccar
      ports:
         - "8082:8082" # Web interface
         - "5055:5055/udp" # GPS device ports (for iOS Traccar Client App)
         - "5055:5055/tcp" # GPS device ports (for iOS Traccar Client App)
         # - "5000-5150:5000-5150/udp" # GPS device ports (adjust as needed)
         # - "5000-5150:5000-5150/tcp" # GPS device ports (adjust as needed)
      volumes:
         - /volume1/docker/traccar/data:/opt/traccar/data
         - /volume1/docker/traccar/conf:/opt/traccar/conf
      # restart: unless-stopped
      environment:
         - TZ=Your_Timezone # Replace with your timezone (e.g., Europe/London)
      #network_mode: host #Alternatively, for easier port access.
