services:
  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:latest
    restart: always
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ${DOCKER_FOLDER}/synapse/data:/data
    networks:
      - local-ai-network
    ports:
      - "4530:8008"

  synapse-admin:
    container_name: synapse-admin
    image: awesometechnologies/synapse-admin:0.10.1
    restart: always
    ports:
      - "4531:80"
    networks:
      - local-ai-network

networks:
  local-ai-network:
    external: true
