services:
  synapse:
    security_opt:
      - "label=disable"
    logging:
      driver: "k8s-file"
    volumes:
      - ${DOCKER_FOLDER}/synapse/data:/data:Z

  synapse-admin:
    security_opt:
      - "label=disable"
    logging:
      driver: "k8s-file"
