services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: $RESTART_POLICY
    ports:
      - "4522:8080"
    volumes:
      - ${DOCKER_FOLDER}/searxng/settings.yml:/etc/searxng/settings.yml
    networks:
      - local-ai-network

networks:
  local-ai-network:
    external: true
