# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  ollama-container:
    image: ollama/ollama
    container_name: ollama
    networks:
      - local-ai-network
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ${DOCKER_FOLDER}/ollama:/root/.ollama

# We create a specific network for these Docker containers to communicate over called local-ai-network
networks:
  local-ai-network:
    external: true
