version: "3.7"

services:
  synapse:
    container_name: synapse
    image: docker.io/matrixdotorg/synapse:latest
    restart: always
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - /volume1/docker/synapse/data:/data
    ports:
      - "4530:8008"
    labels:
      - com.centurylinklabs.watchtower.enable=true

  synapse-admin:
    container_name: synapse-admin
    image: docker.io/awesometechnologies/synapse-admin:0.10.1
    restart: always
    ports:
      - "4531:80"
    labels:
      - com.centurylinklabs.watchtower.enable=true

  element-web:
    container_name: element-web
    image: docker.io/vectorim/element-web:latest
    restart: always
    environment:
      - ELEMENT_WEB_PORT=8080
    volumes:
      - /volume1/docker/synapse/element-web/config.json:/app/config.json:ro
    ports:
      - "4535:8080"
    labels:
      - com.centurylinklabs.watchtower.enable=true
