services:
   nextcloud:
      image: docker.io/nextcloud:32.0.2
      container_name: nextcloud
      restart: $RESTART_POLICY
      ports:
         - "4520:80"
      volumes:
         - ${DOCKER_FOLDER}/nextcloud/data:/var/www/html
      environment:
         - POSTGRES_HOST=${POSTGRES_HOST}
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
         - REDIS_HOST=${REDIS_HOST}
         - REDIS_PORT=${REDIS_PORT}
         - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
         - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
         - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
         - OVERWRITEHOST=${NEXTCLOUD_TRUSTED_DOMAINS}
         - OVERWRITEPROTOCOL=https
      depends_on:
         - db
         - redis

   db:
      image: docker.io/postgres:18.1
      container_name: nextcloud-db
      restart: $RESTART_POLICY
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      volumes:
         - ${DOCKER_FOLDER}/nextcloud/db:/var/lib/postgresql

   redis:
      image: docker.io/redis:8.4.0
      container_name: nextcloud-redis
      restart: $RESTART_POLICY
      volumes:
         - ${DOCKER_FOLDER}/nextcloud/redis:/var/lib/redis

   collabora:
      image: docker.io/collabora/code:latest
      container_name: nextcloud-collabora
      restart: $RESTART_POLICY
      environment:
         - domain=${NEXTCLOUD_TRUSTED_DOMAINS}
         - username=${COLLABORA_USERNAME}
         - password=${COLLABORA_PASSWORD}
         - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      ports:
         - "9980:9980"
